export { default as SignIn } from './user/SignIn';
export { default as SignUp } from './user/SignUp';
export { default as Home } from './core/Home';
export { default as Menu } from './core/Menu';
export { default as Layout } from './core/Layout'
export { default as UserDashBoard } from './user/UserDashBoard'
export { default as PrivateRoute } from './auth/PrivateRoute';
export { default as AdminRoute } from './auth/AdminRoute'
export { default as AdminDashBoard } from './user/AdminDashBoard'
export { default as AddCategory } from './admin/AddCategory';
export { default as AddProduct } from './admin/AddProduct';